import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Vinayak International School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
